(print (substring "abcdef" 0 2))
(print (+ 3 5))
(print
  (- (+ 3 5) (* 12 2)))
(print
  (+ 10 (string->number "5")))
(print #d21)
(print #o25)
(print #x15)
(print #b10101)
(print (string-intersperse '("a" "b" "c" "d") ";"))
(print (string-split "a;b;c;d" ";"))
(define (main args)
  (print "hello world"))
(print (string-append "1" "2"))
(print (cons "1" "2"))
(print
  (if (< 1 2) "yes" "no"))
(cond
  ((< 1 2) "1 < 2")
  ((> 1 2) "1 > 2")
  (else "1 = 2"))
(define l '(1 2 3 4))
(define (add10 n)
  (print (+ n 10)))
(for-each print l)
(for-each add10 l)
(print "blocked to read a line:")
(read-line)
(print "resume")